

color1 = input("Enter a color: ")
place1 = input("Enter a place: ")
adjective1 = input("Enter an adjective: ")
roomofhouse1 = input("Enter a room of a house: ")
food1 = input("Enter a food: ")
adjdestemp1 = input("Enter an adjective describing temperature: ")
adjdestemp2 = input("Enter a different adjective describing temperature: ")
pieceoffurniture = input("Enter a piece of furniture: ")
texture1 = input("Enter an adjective describing texture: ")
texture2 = input("Enter a different adjective describing texture: ")
adjdescibingvolumes = input("Enter an adjective describing a volume: ")
animal = input("Enter an animal: ")

goldilocks = (color1 + 'ilocks:' 
' Once upon a time, there was a little girl with ' + color1 + ' hair. One day when she was walking in the ' + place1 + ' she came across a small house. “Wow! This house is so ' + adjective1 + '!” She said. She knocked on the door but no one answered so she decided to go in. When she walked into the ' + roomofhouse1 + ' she found three plates/bowls of ' + food1 + '. She was hungry so she tasted some food from the first plate. “Oh no! This ' + food1 + ' is too ' + adjdestemp1 + '!" She exclaimed. She tried some from the second plate. “This ' +  food1 + ' is too ' +  adjdestemp2 + '!" She tried the third plate. "Ahh, this is just right," she said and ate it all up! All that food made the girl tired so she went upstairs and found three ' + pieceoffurniture + 's. She tried to get comfortable on the first '+ pieceoffurniture+ ' but, “Agghhh, this ' + pieceoffurniture+ ' is too ' +texture1+ '!” She got up and went over to the next bed. “This ' +pieceoffurniture+ ' is too '+texture2+'!” She was getting really annoyed now and but decided to try the third ' +pieceoffurniture+ '. “This '+pieceoffurniture+ ' is just right!" And she fell asleep right there. When she woke up she heard ' + adjdescibingvolumes+ ' voices. One said “Someone had a bit of my ' + food1+ '!" The next one said “Someone took a bite of my ' +food1+ '!” The third one said “Someone ate all of my ' +food1+ '!” The voices were closer now and the first one said “Someone was using my ' +pieceoffurniture+ '!” The second one said, “I think someone was using my ' +pieceoffurniture+ ' too!” The third one said, “Someone is still using my '+pieceoffurniture+ '!” The girl sat up and came face to face with three ' +animal+'s. She screamed, ran from the house, and never returned.')

#cinderella = ('Cinderella: Once upon a time in a kingdom far away, there lived a girl named Cinderella with two evil stepsisters and a step mother who was rotten to the core. It was the night of a ball, one of the grandest of the land. Cinderella wanted to go to the ball oh so badly but the night before her sisters had ripped up her dress. Sweeping the front of the house, long after her sisters and stepmother had left for the ball, Cinderella heard a ' +adjdescribingvolume+ ' twinkling. In front of her eyes, she was met with a woman with white hair and a' +texture1+ 'dress. She met Cinderella with a kind smile and said “What are you doing here, dear?”Aghast, Cinderella explained the story to her. The woman just smiled and said “Well, I’m your fairy godmother, Cinderella, and I’m here to help you get to the ball.” With the swish of her wand, the fairy godmother transformed Cinderella’s" +color1+ "rags into a"+ color 2+ "ballgown. “I love it but how would I get to the ball?” Cinderella asked. On the curb of the street was a ' +pieceoffurniture+ ' and catching her eye, the fairy godmother brought it over to them with a flick of her hand and after a chant was magicked into a'+food1+ 'carriage. As a'+animal+'scurried by, with another quick movement of her wand, she transformed them into a coachman. “But there’s nothing to drag the carriage,” Cinderella pointed out. “That won’t be a problem for much longer, dear.” The fairy godmother said with a twinkle in her eye. Just like she did before, the godmother whooshed another one of the'+animal+ 'scurrying by from a'+animal+'to a horses. “And of course, how could i forget?” The godmother tapped her chin. Walking over to their front garden, the godmother plucked a'+food1+'from the garden, setting it on the floor. She closed her eyes and said “Bibbity-boppity-boo"'+adjdescribingvolume+'The'+food1+ 'was turned into sparkling glass slippers. The godmother looked to Cinderella and winked. “Off you go now.”')

#littleredridinghood = ('Once upon a time, Little'+color1+'Riding Hood headed into the woods to see her sick grandmother. In her hand, she held a basket with'+food1+'. Her mother prepared it just for her grandmother and it was still'+adjdescribingtemperature1+'. A little after Little'+color1+'Riding Hood embarked on her path to her grandmother’s house, she ran into a wolf with'+texture1+'fur. She tried to walk around him but he kept blocking her path. Frustrated, he huffed and asked her what was in her basket. She refused to look at him, crossing her arms. He repeated himself over and over till he was fed up. He asked her his question again'+adjdescribingvolume+'. This time Little'+color1+'Riding Hood just scoffed, stomping on the wolf’s foot and strutted away.')


print(goldilocks)